import {StyleSheet} from 'react-native';

const Styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFF',
    flex: 1,
  },
  header: {
    height: 64,
    alignItems: 'center',
    paddingTop: 21,
    backgroundColor: '#0154AD',
  },
  text: {
    color: '#FFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  button: {
    margin: 20,
    paddingVertical: 12,
    paddingHorizontal: 30,
    lineHeight: 35,
    textAlign: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FF7E1F',
    borderRadius: 10,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Cairo',
  },
  containerLista: {
    flex: 1,
    backgroundColor: 'white',
    flexDirection: 'row',
    width: '100%',
    height: 50,
    padding: 15,
    marginVertical: 8,
    marginHorizontal: 16,
    alignItems: 'center',
    paddingTop: 8,
  },
  title: {
    color: '#0154AD',
    fontSize: 16,
    textAlign: 'left',
  },
  image: {
    height: 41,
    borderRadius: 50,
    width: 41,
    marginRight: 11,
  },
  textInput: {
    width: '100%',
    flex: 1,
    height: 70,
    color: '#7C8B99',
    fontSize: 15,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'Cairo',
  },
  container2: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: 'grey',
    flexDirection: 'row',
  },
  iconName: {
    height: 25.4,
    width: 25.54,
    alignSelf: 'center',
    paddingRight: 50,
    paddingLeft: 50,
  },
  iconEmail: {
    width: 25.08,
    height: 17.24,
    alignSelf: 'center',
    paddingRight: 50,
    paddingLeft: 50,
  },
  iconFone: {
    width: 24.14,
    height: 23.99,
    alignSelf: 'center',
    paddingRight: 50,
    paddingLeft: 50,
  },
  iconBirthday: {
    width: 26,
    height: 26,
    alignSelf: 'center',
    paddingRight: 50,
    paddingLeft: 50,
  },
  iconCpf: {
    width: 35,
    height: 39,
    alignSelf: 'center',
    paddingRight: 50,
    paddingLeft: 50,
  },
  button2: {
    margin: 20,
    paddingVertical: 12,
    paddingHorizontal: 50,
    lineHeight: 35,
    textAlign: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FF7E1F',
    borderRadius: 10,
    marginTop: 160,
  },
  iconDelete: {
    justifyContent: 'center',
  },
  containerIcon: {
    flex: 1,
    justifyContent: 'center',
    width: 40,
    height: 40,
    alignItems: 'center',
    paddingLeft: 100,
    flexDirection: 'row',
  },
  containerButton: {
    width: '100%',
    height: '40%',
    flex: 1,
  },
  ButtonTour: {
    width: '50%',
    height: '50%',
    flex: 1,
  },
  TextTest: {
    width: '100%',
    flex: 1,
    height: 70,
    color: '#7C8B99',
    fontSize: 15,
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'Cairo',
  },
});

export default Styles;
